FROM node:18

# Instala nodemon de forma global
RUN npm i -g nodemon

# Crea el directorio de la aplicación
RUN mkdir -p /home/app

# Establece el directorio de trabajo
WORKDIR /home/app

# Copia los archivos de la aplicación al contenedor
COPY . /home/app

# Expone el puerto 3000
EXPOSE 3000

# Comando para ejecutar la aplicación con nodemon
CMD ["nodemon", "index.js"]
